name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Write client config
        run: |
          @"
          export const firebaseConfig = {
            apiKey: "AIzaSyDphA090liCwD1C6TDPfjZrZFewnk5Z3yI",
            authDomain: "employee-management-8cb26.firebaseapp.com",
            projectId: "employee-management-8cb26",
            storageBucket: "employee-management-8cb26.firebasestorage.app",
            messagingSenderId: "241361442701",
            appId: "1:241361442701:web:b6b3c26265636382868fc4",
            measurementId: "G-6QSGNVYT4Q",
          };

          export const cloudinaryConfig = {
            cloudName: "dlyktw5s5",
            uploadPreset: "nuxt_unsigned",
          };
          "@ | Set-Content config.js
      - run: npm ci
      - run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Write client config
        run: |
          cat <<EOF > config.js
          export const firebaseConfig = {
            apiKey: "AIzaSyDphA090liCwD1C6TDPfjZrZFewnk5Z3yI",
            authDomain: "employee-management-8cb26.firebaseapp.com",
            projectId: "employee-management-8cb26",
            storageBucket: "employee-management-8cb26.firebasestorage.app",
            messagingSenderId: "241361442701",
            appId: "1:241361442701:web:b6b3c26265636382868fc4",
            measurementId: "G-6QSGNVYT4Q",
          };

          export const cloudinaryConfig = {
            cloudName: "dlyktw5s5",
            uploadPreset: "nuxt_unsigned",
          };
          EOF
      - run: npm ci
      - run: npm run dist:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Write client config
        run: |
          cat <<EOF > config.js
          export const firebaseConfig = {
            apiKey: "AIzaSyDphA090liCwD1C6TDPfjZrZFewnk5Z3yI",
            authDomain: "employee-management-8cb26.firebaseapp.com",
            projectId: "employee-management-8cb26",
            storageBucket: "employee-management-8cb26.firebasestorage.app",
            messagingSenderId: "241361442701",
            appId: "1:241361442701:web:b6b3c26265636382868fc4",
            measurementId: "G-6QSGNVYT4Q",
          };

          export const cloudinaryConfig = {
            cloudName: "dlyktw5s5",
            uploadPreset: "nuxt_unsigned",
          };
          EOF
      - run: npm ci
      - run: npm run dist:linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
